### ISSUE TITLE
Potion Effect Status Labels still push REI

### ISSUE THREAD

**Issue by Shockks** [CammiePone/Leftist-Potions#1]
The space in REI that is usually occupied by the right hand sided potion effect status label is still created, only it is empty:

![image](https://user-images.githubusercontent.com/9029288/149458334-8a686d73-408f-45a5-a2f9-e05ba9fd75ef.png)

Im not sure if this is something that needs to change with REI or Leftists potions. Can it be changed on your side? Ive commented on the existing issue at REI here https://github.com/shedaniel/RoughlyEnoughItems/issues/683

**Comment by CammiePone** [comment]
Ye, I can make a mixin on my end to fix it (I think)

**Comment by CammiePone** [comment]
Mod is kinda redundant now, since REI added the feature a day or two after releasing it, so guess that's pointless now
