### ISSUE TITLE
Potion overlay on left side overlaps inventory GUI

### ISSUE THREAD

**Issue by Karlb2222** [CammiePone/Leftist-Potions#2]
As title states, potion effect indicator overlaps with the inventory GUI
![b1c281b5a13be9e9774b717833cfbce7](https://user-images.githubusercontent.com/76551360/149651085-0446062c-ee59-44c1-b945-fccbc359bdf1.png)

**Comment by CammiePone** [comment]
Only a day or two after releasing the mod, REI added the feature themselves, so the mod is kinda redundant now
